name: iagos-iriscc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - requests
  - python-keycloak
  - cryptography
  - xarray
  - netcdf4
  - h5netcdf
  - h5py
  - matplotlib
  - pandas
  - numpy
  - pyarrow
  - python-dotenv
  - pip:
    - -e .
